# TCL File Generated by Component Editor 21.1
# Tue May 13 00:15:03 EDT 2025
# DO NOT MODIFY


# 
# true_mixed_dual_port_ram "TRUE_MIXED_DUAL_PORT_RAM" v1.0
#  2025.05.13.00:15:03
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module true_mixed_dual_port_ram
# 
set_module_property DESCRIPTION ""
set_module_property NAME true_mixed_dual_port_ram
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME TRUE_MIXED_DUAL_PORT_RAM
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mixed_width_true_dual_port_ram
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file mixed_width_true_dual_port_ram.sv SYSTEM_VERILOG PATH mixed_width_true_dual_port_ram.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter DATA_WIDTH1 INTEGER 32 ""
set_parameter_property DATA_WIDTH1 DEFAULT_VALUE 32
set_parameter_property DATA_WIDTH1 DISPLAY_NAME DATA_WIDTH1
set_parameter_property DATA_WIDTH1 WIDTH ""
set_parameter_property DATA_WIDTH1 TYPE INTEGER
set_parameter_property DATA_WIDTH1 UNITS None
set_parameter_property DATA_WIDTH1 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH1 DESCRIPTION ""
set_parameter_property DATA_WIDTH1 HDL_PARAMETER true
add_parameter ADDRESS_WIDTH1 INTEGER 6 ""
set_parameter_property ADDRESS_WIDTH1 DEFAULT_VALUE 6
set_parameter_property ADDRESS_WIDTH1 DISPLAY_NAME ADDRESS_WIDTH1
set_parameter_property ADDRESS_WIDTH1 WIDTH ""
set_parameter_property ADDRESS_WIDTH1 TYPE INTEGER
set_parameter_property ADDRESS_WIDTH1 UNITS None
set_parameter_property ADDRESS_WIDTH1 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDRESS_WIDTH1 DESCRIPTION ""
set_parameter_property ADDRESS_WIDTH1 HDL_PARAMETER true
add_parameter ADDRESS_WIDTH2 INTEGER 4 ""
set_parameter_property ADDRESS_WIDTH2 DEFAULT_VALUE 4
set_parameter_property ADDRESS_WIDTH2 DISPLAY_NAME ADDRESS_WIDTH2
set_parameter_property ADDRESS_WIDTH2 WIDTH ""
set_parameter_property ADDRESS_WIDTH2 TYPE INTEGER
set_parameter_property ADDRESS_WIDTH2 UNITS None
set_parameter_property ADDRESS_WIDTH2 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDRESS_WIDTH2 DESCRIPTION ""
set_parameter_property ADDRESS_WIDTH2 HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_hps
# 
add_interface avalon_slave_hps avalon end
set_interface_property avalon_slave_hps addressUnits WORDS
set_interface_property avalon_slave_hps associatedClock clock
set_interface_property avalon_slave_hps associatedReset reset
set_interface_property avalon_slave_hps bitsPerSymbol 8
set_interface_property avalon_slave_hps burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_hps burstcountUnits WORDS
set_interface_property avalon_slave_hps explicitAddressSpan 0
set_interface_property avalon_slave_hps holdTime 0
set_interface_property avalon_slave_hps linewrapBursts false
set_interface_property avalon_slave_hps maximumPendingReadTransactions 0
set_interface_property avalon_slave_hps maximumPendingWriteTransactions 0
set_interface_property avalon_slave_hps readLatency 0
set_interface_property avalon_slave_hps readWaitTime 1
set_interface_property avalon_slave_hps setupTime 0
set_interface_property avalon_slave_hps timingUnits Cycles
set_interface_property avalon_slave_hps writeWaitTime 0
set_interface_property avalon_slave_hps ENABLED true
set_interface_property avalon_slave_hps EXPORT_OF ""
set_interface_property avalon_slave_hps PORT_NAME_MAP ""
set_interface_property avalon_slave_hps CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_hps SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_hps addr1 address Input "((ADDRESS_WIDTH1-1)) - (0) + 1"
add_interface_port avalon_slave_hps data_in1 writedata Input "((DATA_WIDTH1-1)) - (0) + 1"
add_interface_port avalon_slave_hps we1 write Input 1
add_interface_port avalon_slave_hps data_out1 readdata Output "((DATA_WIDTH1-1)) - (0) + 1"
set_interface_assignment avalon_slave_hps embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_hps embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_hps embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_hps embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst reset Input 1


# 
# connection point sched_conduit
# 
add_interface sched_conduit conduit end
set_interface_property sched_conduit associatedClock clock
set_interface_property sched_conduit associatedReset reset
set_interface_property sched_conduit ENABLED true
set_interface_property sched_conduit EXPORT_OF ""
set_interface_property sched_conduit PORT_NAME_MAP ""
set_interface_property sched_conduit CMSIS_SVD_VARIABLES ""
set_interface_property sched_conduit SVD_ADDRESS_GROUP ""

add_interface_port sched_conduit addr2 round_key_addr Input 4
add_interface_port sched_conduit data_out2 round_key Output 128

